import * as set from '/script/library/settings.js';

export function LoadTemplate(parent, tab) {
    var dm = set.SettingItem("display.brightness");
    var allmain = document.createElement("div");
    var leftbar = document.createElement("div");
    var faviconbar = document.createElement("div");
    var favicon = document.createElement("img");
    var navbar = document.createElement("div");
    var nbiHome = document.createElement("a");
    var nbiArt = document.createElement("a");
    var nbiCate = document.createElement("a");
    var nbiTag = document.createElement("a");
    var nbiApp = document.createElement("a");
    var imgHome = document.createElement("img");
    var imgArt = document.createElement("img");
    var imgCate = document.createElement("img");
    var imgTag = document.createElement("img");
    var imgApp = document.createElement("img");
    var paraHome = document.createElement("p");
    var paraArt = document.createElement("p");
    var paraCate = document.createElement("p");
    var paraTag = document.createElement("p");
    var paraApp = document.createElement("p");
    var miin = document.createElement("div");
    var rightpart = document.createElement("div");
    var main = document.createElement("div");
    parent.appendChild(allmain);
    allmain.appendChild(leftbar);
    allmain.appendChild(rightpart);
    allmain.classList.add("template-main");
    leftbar.appendChild(faviconbar);
    leftbar.appendChild(navbar);
    leftbar.appendChild(miin);
    leftbar.classList.add("template-leftbar");
    faviconbar.appendChild(favicon);
    faviconbar.classList.add("template-faviconbar");
    favicon.classList.add("template-favicon");
    favicon.src = `/asset/${dm}/images-svg/github.svg`;
    navbar.appendChild(nbiHome);
    navbar.appendChild(nbiArt);
    navbar.appendChild(nbiCate);
    navbar.appendChild(nbiTag);
    navbar.appendChild(nbiApp);
    navbar.classList.add("template-navbar");
    nbiHome.href = "/";
    nbiHome.id = "tab-home";
    nbiHome.classList.add("template-navitem");
    nbiHome.appendChild(imgHome);
    nbiHome.appendChild(paraHome);
    imgHome.classList.add("template-navimage");
    imgHome.src = `/asset/${dm}/images-svg/house.svg`;
    paraHome.innerText = '主页';
    nbiArt.href = "/articles";
    nbiArt.id = "tab-articles";
    nbiArt.classList.add("template-navitem");
    nbiArt.appendChild(imgArt);
    nbiArt.appendChild(paraArt);
    imgArt.classList.add("template-navimage");
    imgArt.src = `/asset/${dm}/images-svg/article.svg`;
    paraArt.innerText = '文章';
    nbiCate.href = "/categories";
    nbiCate.id = "tab-categories";
    nbiCate.classList.add("template-navitem");
    nbiCate.appendChild(imgCate);
    nbiCate.appendChild(paraCate);
    imgCate.classList.add("template-navimage");
    imgCate.src = `/asset/${dm}/images-svg/categories.svg`;
    paraCate.innerText = '分类';
    nbiTag.href = "/tags";
    nbiTag.id = "tab-tags";
    nbiTag.classList.add("template-navitem");
    nbiTag.appendChild(imgTag);
    nbiTag.appendChild(paraTag);
    imgTag.classList.add("template-navimage");
    imgTag.src = `/asset/${dm}/images-svg/tag.svg`;
    paraTag.innerText = '标签';
    nbiApp.href = "/applications";
    nbiApp.id = "tab-applications";
    nbiApp.classList.add("template-navitem");
    nbiApp.appendChild(imgApp);
    nbiApp.appendChild(paraApp);
    imgApp.classList.add("template-navimage");
    imgApp.src = `/asset/${dm}/images-svg/applications.svg`;
    paraApp.innerText = '应用';
    rightpart.appendChild(main);
    rightpart.classList.add("template-rightpart");
    main.id = "main";
    main.classList.add("template-rightmain");
    miin.id = "miin";
    miin.classList.add("template-miinbar");
}